@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.refinedrelocation.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;