@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.refinedrelocation.compat;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;