@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.blay09.mods.refinedrelocation.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;